

def join_horizontally(images):
    """Return image generated by joining the given images horizontally."""

    x_dims = [image.shape[0] for image in images]
    y_dims = [image.shape[1] for image in images]

    x_dim = max(x_dims)
    y_dim = sum(y_dims)

    output_image = np.zeros((x_dim, y_dim, 3), dtype=np.uint8)

    offset = 0
    for n, image in enumerate(images):
        i_xdim, i_ydim, _ = image.shape
        output_image[0:i_xdim, offset:i_ydim+offset] = image
        offset = offset + i_ydim

    return output_image.view(Image)


def join_vertically(images):
    """Return image generated by joining the given images vertically."""

    x_dims = [image.shape[0] for image in images]
    y_dims = [image.shape[1] for image in images]

    x_dim = sum(x_dims)
    y_dim = max(y_dims)

    output_image = np.zeros((x_dim, y_dim, 3), dtype=np.uint8)

    offset = 0
    for n, image in enumerate(images):
        i_xdim, i_ydim, _ = image.shape
        output_image[offset:i_xdim+offset, 0:i_ydim] = image
        offset = offset + i_xdim

    return output_image.view(Image)
