"""Test indexing of plots."""

import os
import random
import argparse

from collections import defaultdict

import dtoolcore

import numpy as np

from jicbioimage.core.image import Image

from dtoolutils import (
    temp_working_dir,
    stage_outputs
)


def ensure_uri(path_or_uri):

    if ':' in path_or_uri:
        return path_or_uri
    else:
        return "disk:{}".format(path_or_uri)


def join_horizontally(images):
    """Return image generated by joining the given images horizontally."""

    x_dims = [image.shape[0] for image in images]
    y_dims = [image.shape[1] for image in images]

    x_dim = max(x_dims)
    y_dim = sum(y_dims)

    output_image = np.zeros((x_dim, y_dim, 3), dtype=np.uint8)

    offset = 0
    for n, image in enumerate(images):
        i_xdim, i_ydim, _ = image.shape
        output_image[0:i_xdim, offset:i_ydim+offset] = image
        offset = offset + i_ydim

    return output_image.view(Image)


def join_vertically(images):
    """Return image generated by joining the given images vertically."""

    x_dims = [image.shape[0] for image in images]
    y_dims = [image.shape[1] for image in images]

    x_dim = sum(x_dims)
    y_dim = max(y_dims)

    output_image = np.zeros((x_dim, y_dim, 3), dtype=np.uint8)

    offset = 0
    for n, image in enumerate(images):
        i_xdim, i_ydim, _ = image.shape
        output_image[offset:i_xdim+offset, 0:i_ydim] = image
        offset = offset + i_xdim

    return output_image.view(Image)


def generate_plots_image(dataset, dates_to_identifiers):

    images = []
    sorted_dates = sorted(dates_to_identifiers)

    for date in sorted_dates:
        identifier = dates_to_identifiers[date]
        image_abspath = dataset.item_content_abspath(identifier)
        image = Image.from_file(image_abspath)
        images.append(image)

    output_image = join_horizontally(images)

    return output_image


def generate_plot_image_list(dataset, dates_to_identifiers):

    images = []
    sorted_dates = sorted(dates_to_identifiers)

    for date in sorted_dates:
        identifier = dates_to_identifiers[date]
        image_abspath = dataset.item_content_abspath(identifier)
        image = Image.from_file(image_abspath)
        images.append(image)

    return images


def index_plots_by_label(dataset):
    """Return dictionary of dictionaries such that all plots are indexed by
    a unique label, and then by date, so any individual plot is:

    index_by_label[label][date]."""

    date_overlay = dataset.get_overlay('date')
    ordering_overlay = dataset.get_overlay('ordering')
    plot_number_overlay = dataset.get_overlay('plot_number')

    def generate_plot_label(identifier):
        return "{}_{}".format(
            ordering_overlay[identifier],
            plot_number_overlay[identifier]
        )

    indexed_by_label = defaultdict(dict)
    for i in dataset.identifiers:
        label = generate_plot_label(i)
        date = date_overlay[i]
        indexed_by_label[label][date] = i

    return indexed_by_label


def arrange_in_grid(image_series):

    n_rows = len(image_series)
    n_cols = len(image_series[0])

    x_dims = []
    y_dims = []
    for row in image_series:
        for image in row:
            x_dim, y_dim, _ = image.shape
            x_dims.append(x_dim)
            y_dims.append(y_dim)

    xmax = max(x_dims)
    ymax = max(y_dims)

    output_x_dim = max(x_dims) * n_rows
    output_y_dim = max(y_dims) * n_cols

    output_image = np.zeros((output_x_dim, output_y_dim, 3), dtype=np.uint8)

    x_offset = 0
    for row in image_series:
        y_offset = 0
        for image in row:
            i_xdim, i_ydim, _ = image.shape
            output_image[x_offset:x_offset+i_xdim, y_offset:i_ydim+y_offset] = image
            y_offset = y_offset + ymax
        x_offset = x_offset + xmax

    return output_image.view(Image)


def explore_plot_indexing(dataset, working_dir):

    indexed_by_label = index_plots_by_label(dataset)

    complete_sets = [k for k, v in indexed_by_label.items() if len(v) == 5]

    sample_labels = random.sample(complete_sets, 10)

    time_progression_image_series = [
        generate_plot_image_list(dataset, indexed_by_label[l])
        for l in sample_labels
    ]

    joined_image = arrange_in_grid(time_progression_image_series)

    # joined_image = join_vertically(time_progression_images)

    output_fpath = os.path.join(working_dir, 'joined.png')
    with open(output_fpath, 'wb') as fh:
        fh.write(joined_image.png())

    return [('joined.png', {})]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--dataset-uri')
    parser.add_argument('--output-uri')

    args = parser.parse_args()

    dataset_uri = ensure_uri(args.dataset_uri)
    output_uri = ensure_uri(args.output_uri)
    dataset = dtoolcore.DataSet.from_uri(dataset_uri)
    output_dataset = dtoolcore.ProtoDataSet.from_uri(output_uri)

    with temp_working_dir() as working_dir:
        outputs = explore_plot_indexing(dataset, working_dir)
        stage_outputs(
            outputs,
            working_dir,
            dataset,
            output_dataset,
            [],
            None
        )


if __name__ == '__main__':
    main()
